# where we process files
%.h.gch: %.h
	$(EE_CC) $(EE_CFLAGS) $(EE_INCS) -c $< -o $@	

%.ttf.h: %.ttf
	bin2c $< $@ $(subst /,_,$(subst .,_,$<))

%.raw.h: %.raw
	bin2c $< $@ $(subst /,_,$(subst .,_,$<))